### ISSUE TITLE
wp-fuzz.txt is not exsit

### ISSUE THREAD

**Issue by eng-abdo-ali** [anmolksachan/TheTimeMachine#4]
I can't find this file (wp-fuzz.txt)

**Comment by eng-abdo-ali** [comment]
![image](https://user-images.githubusercontent.com/43831505/154824258-5095bd98-5332-4e6d-ab60-c0aba7d9be92.png)

**Comment by anmolksachan** [comment]
wp-fuzz.txt updated
:)
