### ISSUE TITLE
Error while runnning the tool

### ISSUE THREAD

**Issue by marinus95** [anmolksachan/TheTimeMachine#8]
raceback (most recent call last):
  File "/root/opt/TheTimeMachine/thetimemachine.py", line 141, in <module>
    file = open(targetFile, 'w')
           ^^^^^^^^^^^^^^^^^^^^^
<img width="598" alt="thetimemachine issue" src="https://github.com/user-attachments/assets/026a47dc-ae78-46bf-995b-dd9e769a3d85">

**Comment by anmolksachan** [comment]
Hi @marinus95 

Can you share more details? as in the command with the path you're trying to run from? Also are you root?

Meanwhile, here are some things you can check:
1. Verify targetFile Definition: Make sure that targetFile is properly defined before you attempt to open it. It should be a string containing the path and filename.
2. Check Path Validity: Ensure that the path in targetFile exists, especially if it’s a directory that may need special permissions (e.g., /root).
3. Permission Issue: If you're writing to a directory like /root, you may not have the necessary permissions. Try running the script with elevated permissions or changing targetFile to a directory you know you can write to, like /tmp or your user directory.
4. Check File Mode: Make sure that 'w' is the mode you intend to use. This will overwrite the file if it exists. If you want to append instead, use 'a'.

Thanks!

**Comment by marinus95** [comment]
1. Checked
2. Path to Target File exists!
3. I am already root already and when i run it again. it gives me the following error
4. It was all fine , from yesterday it gave me this error. I tried deleting and reinstalling it again. Gives me same following error

<img width="449" alt="image" src="https://github.com/user-attachments/assets/7830c5fe-2153-4524-ba76-0c53a38e6b4a">

**Comment by marinus95** [comment]
I tried fixing the code

**Comment by anmolksachan** [comment]
Is the issue while launching or during runtime?

**Comment by marinus95** [comment]
During runtime.

**Comment by marinus95** [comment]
During Runtime i face this issue. the tool runs , it checks internet connection.

**Comment by marinus95** [comment]
while Runtime i'm facing this issue, its the same with my other system and friends as well. I have checked it 3 other systems. So this is error i'm getting. I have copied pasted it below, replacing the target name with target . 

Checking Your Internet Connection...

The Time Machine got WayBackMachine's Status Code as: 200

OK!, The Time Machine Will Work                                                                
Internet Connection is Active.                                                                 

Target Loaded: <target> gets loaded

Fetching URLs from The Time Machine :P 
Have Patience this may take some time depending on the size of asset
[Dont press Enter or anykey while TheTimeMachine is Fetching URLs]
Current time : 2024-10-29 16:50:25.599733
Data will be stored in content/target.com
Storing links in : content/target_URLs.txt
Completed

Found 14 instances in The Time Machine, Stored in  content/target_URLs.txt
Traceback (most recent call last):
  File "/root/opt/TheTimeMachine/thetimemachine.py", line 167, in <module>
    output = matches.group()
             ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by anmolksachan** [comment]
Hi,

It looks like the website from where the data is gathered is currently down/ not servicing the requests. I'll investigate further about the alternatives to fix the issue. Attaching the image for reference.

I'll let this issue stay open until there is a fix/ website starts working.

Thanks for posting the issue. 🍻 appreciate that!

![image](https://github.com/user-attachments/assets/f360ab3a-df2e-4aec-a6e7-afcc3ffc880e)

**Comment by marinus95** [comment]
Thankyou! Will wait for this issue to be resolved. And Btw your tool is amazing mahn! Have been using this tool for many assessment , does the work with ease. Will be awaiting for it to get resolved soon

**Comment by anmolksachan** [comment]
Hi @marinus95 

The service is online and working. The tools should be working fine now!

![image](https://github.com/user-attachments/assets/52d66352-a929-4098-97bf-8f5077ea39d6)


Thanks!
